config/routes.rb
Forgeos::CommerceFront::Engine.routes.draw do
  resource :user do
    member do
      get :activate
      get :new_password
      get :forgotten_password
      put :update_password
      post :reset_password
    end

    resources :orders
    resources :addresses

    resources :address_deliveries, :controller => :addresses, :as => :addresses
    resources :address_invoices, :controller => :addresses, :as => :addresses
  end
end

app/models/user.rb
load File.join(Gem.loaded_specs['forgeos_commerce'].full_gem_path, 'app', 'models', 'user.rb')
User.class_eval do
  validates_confirmation_of :email, :if => :confirm_email?

  def confirm_email?
    Forgeos::CONFIG[:account]['checkout_quick_create']
  end

  def skip_presence_of_lastname?
    not Forgeos::CONFIG[:account]['checkout_quick_create']
  end

  def skip_presence_of_firstname?
    not Forgeos::CONFIG[:account]['checkout_quick_create']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :only => [:show, :update]
  before_filter :get_user, :only => [:show, :update]
  before_filter :manage_address, :only => [:update]
  around_filter FieldErrorProcChanger.new(
    Proc.new do |html_tag, instance|
      error_message = instance.object.errors.on(instance.method_name)
      if error_message && !(html_tag =~ /^<label|type="hidden"/)
        if html_tag.match(/class="/)
          html_tag.gsub!(/class="/, "class=\"error_on_this_field ")
        else
          html_tag.gsub!(/\/>$/, " class=\"error_on_this_field\"\/>")
        end
        html_tag = "#{html_tag}<div class=\"field_error\">#{error_message.is_a?(Array) ? error_message.first : error_message}</div>"
      else
        html_tag
      end
    end
  ), :only => [:create, :update]

  def show
  end

  def new
    @user = User.new(params[:user])
  end

  def create
    cookies.delete :auth_token
    @user = User.new(params[:user])
    password = params[:user][:password]
    if (not Forgeos::CONFIG[:account]['checkout_quick_create'] or not password) and Forgeos::CONFIG[:account]['password_generated']
      password = generate_password(10)
      @user.email_confirmation = @user.email if @user.respond_to?('email_confirmation=')
      @user.password = password
      @user.password_confirmation = password
    end
    if @user.save
      if @generated_password
        Notifier.deliver_validation_user_account(@user, password)
      else
        @user.activate
        PersonSession.create(@user,true)
      end
      flash[:notice] = I18n.t('success', :scope => [:user, :create])
      redirect_to_stored_location(login_path)
    else
      Rails.logger.info("\033[01;33m#{@user.errors.inspect}\033[0m")
      if @user.errors.on(:civility)
        flash[:error] = 'Veuillez préciser votre civilité'
      else
        flash[:error] = I18n.t('error', :scope => [:user, :create])
      end
      render :action => 'new'
    end
  end

  def activate
    unless params[:activation_code].blank?
      user = User.find_by_perishable_token(params[:activation_code])
      if user
        if user.active?
          flash[:warning] = I18n.t('already_active', :scope => [:user, :activate])
          return redirect_to(:root)
        end
        user.activate
        user.reset_perishable_token!
        PersonSession.create(user, true)
        flash[:notice] = I18n.t('success', :scope => [:user, :activate])
        return redirect_to(:action => :show)
      end
    end
    flash[:error] = I18n.t('error', :scope => [:user, :activate])
    redirect_to(:root)
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = I18n.t('success', :scope => [:user, :update])
    else
      flash[:error] = I18n.t('error', :scope => [:user, :update])
    end
    render(:action => :show)
  end

  def forgotten_password
  end

  def reset_password
    user = User.find_by_email(params[:email])
    unless user
      flash[:warning] = I18n.t('unknown_user', :scope => [:user, :reset_password], :email => params[:email])
      return redirect_to(:action => :forgotten_password)
    end
    begin
      Notifier.deliver_reset_password(user)
      flash[:notice] = I18n.t('success', :scope => [:user, :reset_password])
    rescue StandardError
      flash[:error] = I18n.t('error', :scope => [:user, :reset_password])
    end
    redirect_to(:root)
  end

  def new_password
    @user = User.find_by_perishable_token(params[:user_token])
    unless @user
      flash[:error] = I18n.t('error', :scope => [:user, :new_password])
      redirect_to(:root)
    end
    @user.activate
    @user.reset_perishable_token!
  end

  def update_password
    @user = User.find_by_perishable_token(params[:user_token])
    unless @user
      flash[:error] = I18n.t('error', :scope => [:user, :new_password])
      redirect_to(:root)
    end
    @user.reset_perishable_token!
    if @user.update_attributes(params[:user].reject{|k, v| !k.to_s.match(/^password/)})
      flash[:notice] = I18n.t('success', :scope => [:user, :update])
      redirect_to(login_path)
    else
      flash[:error] = I18n.t('error', :scope => [:user, :update])
      render(:action => :new_password)
    end
  end

  private
  def generate_password(size)
    s = ""
    size.times { s << (i = Kernel.rand(62); i += ((i < 10) ? 48 : ((i < 36) ? 55 : 61 ))).chr }
    @generated_password = true
    return s
  end

  def manage_address
    if params[:user] and params[:user][:address_invoice_attributes]
      params[:user][:address_invoice_attributes][:name] = params[:user][:lastname]
      params[:user][:address_invoice_attributes][:firstname] = params[:user][:firstname]
      params[:user][:address_invoice_attributes][:designation] = 'Première adresse'
      params[:user][:address_invoice_attributes][:civility] = params[:user][:civility]
    end
  end

  def get_user
    @user = current_user
    unless @user.is_a?(User)
      if @user.is_a?(Administrator)
        flash[:warning] = t(:administrator_warning)
        if request.referer
          return redirect_to(:back)
        else
          return redirect_to(:root)
        end
      else
        flash[:error] = t(:not_authorized)
        return render(:text => '', :status => 401, :layout => true)
      end
    end
  end

end

app/views/users/_edit_form.html.haml
.myaccount
  - form_for(@user, :url => user_path, :html => { :multipart => true, :autocomplete => false }) do |f|
    .profile
      %h2
        = t(:profile, :scope => [:user, :part]).capitalize
      .grid_5
        - login_field = Forgeos::CONFIG[:login]['login_field']
        = f.label(login_field, t(:uid, :scope => :user).capitalize)
        = f.text_field(login_field)
      .clear
      //.grid_5
      = password_fields(f)
      .clear
      - if Forgeos::CONFIG[:newsletter]['active']
        .grid_5.newsletter
          = f.check_box(:newsletter)
          = f.label(:newsletter, t(:i_want, :scope => :newsletter).capitalize)
        .clear

      - if Forgeos::CONFIG[:account]['avatar']['active']
        .avatar
          - current_user.build_avatar unless current_user.avatar
          - f.fields_for :avatar do |avatar|
            = display_avatar(current_user.avatar)
            = avatar.file_field :uploaded_data
        .clear
    .coord
      %h2
        = t(:infos, :scope => [:user, :part]).capitalize
      .grid_5
        = f.label :civility, "#{t(:civility, :count => 1).capitalize} <em>*</em>"
        = f.select :civility, options_for_select([['Mr',0],['Mme',1],['Mlle',2],['Société',3]])
      .clear

      .grid_5
        = f.label :lastname, "#{t(:lastname).capitalize} <em>*</em>"
        = f.text_field :lastname
      .clear
      .grid_5
        = f.label :firstname, "#{t(:firstname).capitalize} <em>*</em>"
        = f.text_field :firstname
      .clear
      .grid_5
        = f.label :phone, "#{t(:phone).capitalize} <em>*</em>"
        = f.text_field :phone
      .clear

    .address
      - multiple_addresses = Forgeos::CONFIG[:addresses]['multiple_addresses']
      - if multiple_addresses
        - @user.build_address_delivery unless @user.address_delivery
        = render :partial => '/addresses/multiple_address_form', :locals => {:address => @user.address_invoice}
      - else
        %h2= t(:address, :count => 1, :scope => [:user, :part]).capitalize
        - f.object.build_address_invoice unless f.object.address_invoice
        - f.fields_for :address_invoice do |address|
          = render :partial => '/addresses/address_form', :locals => {:f => address}
    .requiredinfo
      * #{t(:mandatory_field, :count => 2)}
    = f.submit t('action', :scope => [:user, :update])
  .clear

app/views/users/_form_create.html.haml
- content_for(:title, t('action', :scope => [:user, :create]))
- form_for @user, :html => { :autocomplete => 'on'}, :url => user_path do |f|
  .person-session-form
    .grid_2
      = f.label(:civility, "#{t(:civility, :count => 1)} <span class='required'>*<span>")
    .grid_4
      = f.radio_button :civility, 0
      %span M
      = f.radio_button :civility, 1
      %span Mme
      = f.radio_button :civility, 2
      %span Mlle
      = f.radio_button :civility, 3
      %span Société
    - [:lastname, :firstname, :email].each do |key|
      .grid_2
        = f.label key, "#{t(key)} <span class='required'>*<span>"
      .grid_4
        = f.text_field key
      .clear
    - unless Forgeos::CONFIG[:account]['password_generated']
      = password_fields(f)
    .grid_4.prefix_2
      = f.submit t('action', :scope => [:user, :create])
    .clear
%p.mandatory-field
  * #{t(:mandatory_field, :count => 2)}

app/views/users/_form_quick_create.html.haml
- content_for(:title, t('action', :scope => [:user, :create]))
- form_for @user, :html => { :autocomplete => 'on'}, :url => user_path do |f|
  = hidden_field_tag :quick, 1
  .person-session-form
    - [:email, :email_confirmation].each do |key|
      .grid_2
        = f.label key, "#{t(key)} <span class='required'>*<span>"
      .grid_4
        = f.text_field key
      .clear
    = password_fields(f, :label_class => 'grid_2', :input_class => 'grid_4', :field_class=> nil, :password_label => "#{t(:password)} <span class='required'>*<span>", :confirmation_label => "#{t(:password_confirmation)} <span class='required'>*<span>")
    .grid_4.prefix_2
      = f.submit t('action', :scope => [:user, :create])
    .clear
%p.mandatory-field
  * #{t(:mandatory_field, :count => 2)}

app/views/users/_login_or_new.html.haml
.account-area
  .grid_7.login
    %h2= t('new', :scope => [:person_session, :action])
    = render :partial => '/person_sessions/form'
  .prefix_2.grid_7
    %h2= t('create', :scope => [:user, :action])
    - if Forgeos::CONFIG[:account]['checkout_quick_create'] and params[:quick]
      = render :partial => '/users/form_quick_create', :locals => {:btn => 'create'}
    - else
      = render :partial => '/users/form_create', :locals => {:btn => 'create'}

app/views/users/forgotten_password.html.haml
.account-area
  .prefix_4.grid_8
    %h2= t(:forgotten_password, :scope => [:user, :action]).capitalize
    - form_tag(reset_password_user_path, :html => { :autocomplete => false }, :class => 'account-form') do
      .grid_2
        = label_tag(:email, t(:email))
      .grid_5
        = text_field_tag(:email)
      .grid_5.prefix_2
        = submit_tag(t('action', :scope => [:user, :reset_password]), :id => 'forgotten_password_submit')
      .clear
  .clear

app/views/users/new.html.haml
= render :partial => '/users/login_or_new'

app/views/users/new_password.html.haml
.account-area.new_password
  .prefix_4.grid_8
    %h2= t('new_password', :scope => [:user, :action]).capitalize
    - form_for(@user, :url => update_password_user_path, :html => { :autocomplete => false }) do |f|
      = hidden_field_tag :user_token, f.object.perishable_token
      = password_fields(f, :label_class => 'grid_3', :input_class => 'grid_4')
      .grid_5.prefix_2
        = f.submit t('reset_password', :scope => [:user, :action])
      .clear
  .clear

app/views/users/show.html.haml
= render :partial => 'users/edit_form.html.haml'