config/routes.rb
Forgeos::CommerceFront::Engine.routes.draw do
  resource :user do
    member do
      get :activate
      get :new_password
      get :forgotten_password
      put :update_password
      post :reset_password
    end

    resources :orders
    resources :addresses

    resources :address_deliveries, :controller => :addresses, :as => :addresses
    resources :address_invoices, :controller => :addresses, :as => :addresses
  end
end

app/controllers/person_sessions_controller.rb
class PersonSessionsController < ApplicationController

  def new
    @person_session = PersonSession.new
    @user = User.new(params[:user])
    session[:return_to] = params[:return_to] if params[:return_to].present?
  end

  def create
    @person_session = PersonSession.new(params[:person_session])
    if @person_session.save
      redirect_to_stored_location(:user)
      flash[:notice] = t('log.in.success').capitalize
    else
      flash[:error] = t('log.in.failed').capitalize
      redirect_to_stored_location do
        @user = User.new
        render :action => :new
      end
    end
  end

end

app/views/person_sessions/_form.html.haml
- form_for(@person_session || PersonSession.new, :url => person_session_path, :html => { :class => 'account-form' }) do |f|
  .person-session-form
    .grid_2
      = f.label :email, "#{t(:email)} <span class='required'>*</span>"
    .grid_4
      = f.text_field :email
    .clear
    .grid_2
      = f.label :password, "#{t(:password)} <span class='required'>*</span>"
    .grid_4
      = f.password_field :password
    .clear
    .grid_4.prefix_2
      - link_to forgotten_password_user_path, :id => 'reset_password_link' do
        = t('get_forgotten_password').capitalize
    .grid_4.prefix_2
      = f.check_box :remember_me, :value => '1'
      = f.label :remember_me, t(:remember_me).capitalize, :class => 'remember'
      %br
      = f.submit t('log.in.action').capitalize, :class => 'submit_contact'
    .clear
%p.mandatory-field
  * #{t(:mandatory_field, :count => 2)}

app/views/person_sessions/new.html.haml
= render :partial => '/users/login_or_new'

app/views/person_sessions/new_reset_password.html.haml
%h2 Récupérer un nouveau mot de passe
- form_tag :action => 'reset_admin_password' do
  %fieldset.account-form
    = label_tag :email, I18n.t('email').capitalize
    = text_field_tag 'email', nil, :class => 'text'
    = submit_tag 'envoyer', :class => 'submit-connexion commander'
    = link_to "Retour à la page précédente", :action => 'new'